package com.example.transactionstarter.clientflow.controller;

import com.example.transactionstarter.clientflow.dto.InitiatePaymentRequest;
import com.example.transactionstarter.clientflow.dto.InitiatePaymentResponse;
import com.example.transactionstarter.clientflow.service.ClientTransactionService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Entry point for clients who want to pay without manually supplying a
 * customerId or transactionId - both are generated by the backend
 * (see {@link com.example.transactionstarter.idgeneration.service.IdGenerator}).
 */
@RestController
@RequestMapping("/api/clientflow")
public class ClientTransactionController {

    private final ClientTransactionService clientTransactionService;

    public ClientTransactionController(ClientTransactionService clientTransactionService) {
        this.clientTransactionService = clientTransactionService;
    }

    @PostMapping("/payments")
    public ResponseEntity<InitiatePaymentResponse> initiatePayment(@Valid @RequestBody InitiatePaymentRequest request) {
        return ResponseEntity.ok(clientTransactionService.initiatePayment(request));
    }
}
