package com.example.transactionstarter.society.actor.domain;

import com.example.transactionstarter.society.common.IdGenerator;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * An external service provider (club house, salon, EV charging, canteen,
 * etc.) that can receive settlements for society services. The ID is
 * generated by the backend from the business name and category.
 */
@Entity
@Table(name = "merchants")
public class Merchant {

    @Id
    @Column(updatable = false, nullable = false)
    private String id;

    @Column(nullable = false)
    private String businessName;

    @Column(nullable = false)
    private String category;

    @Column(nullable = false)
    private String settlementAccount;

    protected Merchant() {
        // required by JPA
    }

    public Merchant(String businessName, String category, String settlementAccount) {
        this.id = IdGenerator.generateMerchantId(businessName, category);
        this.businessName = businessName;
        this.category = category;
        this.settlementAccount = settlementAccount;
    }

    public String getId() {
        return id;
    }

    public String getBusinessName() {
        return businessName;
    }

    public String getCategory() {
        return category;
    }

    public String getSettlementAccount() {
        return settlementAccount;
    }
}
