package com.example.transactionstarter.society.actor.domain;

import com.example.transactionstarter.society.common.IdGenerator;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Property/facility manager who can raise ad-hoc charges (damage
 * penalties, event fees). The ID is generated by the backend from the
 * society ID and name.
 */
@Entity
@Table(name = "property_managers")
public class PropertyManager {

    @Id
    @Column(updatable = false, nullable = false)
    private String id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String societyId;

    protected PropertyManager() {
        // required by JPA
    }

    public PropertyManager(String name, String societyId) {
        this.id = IdGenerator.generatePropertyManagerId(name, societyId);
        this.name = name;
        this.societyId = societyId;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getSocietyId() {
        return societyId;
    }
}
