package com.example.transactionstarter.society.actor.domain;

import com.example.transactionstarter.idgeneration.service.IdGenerator;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * A resident/flat owner who pays maintenance, utility and one-time dues.
 * The ID is generated by the backend from the flat ID and name; it is
 * never supplied by the client.
 */
@Entity
@Table(name = "residents")
public class Resident {

    @Id
    @Column(updatable = false, nullable = false)
    private String id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String flatId;

    @Column(nullable = false, length = 32)
    private String contact;

    protected Resident() {
        // required by JPA
    }

    public Resident(String name, String flatId, String contact) {
        this.id = IdGenerator.generateResidentId(name, flatId);
        this.name = name;
        this.flatId = flatId;
        this.contact = contact;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getFlatId() {
        return flatId;
    }

    public String getContact() {
        return contact;
    }
}
