package com.example.transactionstarter.society.actor.domain;

import com.example.transactionstarter.society.common.IdGenerator;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Gate/security staff. They do not handle money directly, but their
 * actions (guest entry, amenity usage) can trigger a billable event. The
 * ID is generated by the backend from the society ID and name.
 */
@Entity
@Table(name = "security_guards")
public class SecurityGuard {

    @Id
    @Column(updatable = false, nullable = false)
    private String id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String societyId;

    protected SecurityGuard() {
        // required by JPA
    }

    public SecurityGuard(String name, String societyId) {
        this.id = IdGenerator.generateGuardId(name, societyId);
        this.name = name;
        this.societyId = societyId;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getSocietyId() {
        return societyId;
    }
}
