package com.example.transactionstarter.society.actor.domain;

import com.example.transactionstarter.idgeneration.service.IdGenerator;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Society admin/treasurer/management-committee member who can raise
 * maintenance and utility bills for residents. The ID is generated by the
 * backend from the society ID and name.
 */
@Entity
@Table(name = "society_admins")
public class SocietyAdmin {

    @Id
    @Column(updatable = false, nullable = false)
    private String id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String societyId;

    @Column(nullable = false)
    private String role;

    protected SocietyAdmin() {
        // required by JPA
    }

    public SocietyAdmin(String name, String societyId, String role) {
        this.id = IdGenerator.generateAdminId(name, societyId);
        this.name = name;
        this.societyId = societyId;
        this.role = role;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getSocietyId() {
        return societyId;
    }

    public String getRole() {
        return role;
    }
}
