package com.example.transactionstarter.society.billing.dto;

import com.example.transactionstarter.society.billing.domain.PaymentHead;
import com.example.transactionstarter.transaction.domain.CurrencyCode;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;

/** Data needed to raise a new bill for a resident. No bill ID is accepted; it is generated by the backend. */
public class CreateBillRequest {

    @NotBlank(message = "residentId is required")
    private String residentId;

    @NotBlank(message = "raisedBy is required")
    private String raisedBy;

    @NotNull(message = "head is required")
    private PaymentHead head;

    @NotBlank(message = "description is required")
    private String description;

    @NotNull(message = "amount is required")
    @DecimalMin(value = "0.01", message = "amount must be greater than zero")
    private BigDecimal amount;

    @NotNull(message = "currency is required")
    private CurrencyCode currency;

    public CreateBillRequest() {
    }

    public CreateBillRequest(String residentId, String raisedBy, PaymentHead head, String description, BigDecimal amount, CurrencyCode currency) {
        this.residentId = residentId;
        this.raisedBy = raisedBy;
        this.head = head;
        this.description = description;
        this.amount = amount;
        this.currency = currency;
    }

    public String getResidentId() {
        return residentId;
    }

    public void setResidentId(String residentId) {
        this.residentId = residentId;
    }

    public String getRaisedBy() {
        return raisedBy;
    }

    public void setRaisedBy(String raisedBy) {
        this.raisedBy = raisedBy;
    }

    public PaymentHead getHead() {
        return head;
    }

    public void setHead(PaymentHead head) {
        this.head = head;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public CurrencyCode getCurrency() {
        return currency;
    }

    public void setCurrency(CurrencyCode currency) {
        this.currency = currency;
    }
}
