package com.example.transactionstarter.society.actor.controller;

import com.example.transactionstarter.society.actor.dto.CreateMerchantRequest;
import com.example.transactionstarter.society.actor.dto.CreatePropertyManagerRequest;
import com.example.transactionstarter.society.actor.dto.CreateResidentRequest;
import com.example.transactionstarter.society.actor.dto.CreateSecurityGuardRequest;
import com.example.transactionstarter.society.actor.dto.CreateSocietyAdminRequest;
import com.example.transactionstarter.society.actor.dto.MerchantResponse;
import com.example.transactionstarter.society.actor.dto.PropertyManagerResponse;
import com.example.transactionstarter.society.actor.dto.ResidentResponse;
import com.example.transactionstarter.society.actor.dto.SecurityGuardResponse;
import com.example.transactionstarter.society.actor.dto.SocietyAdminResponse;
import com.example.transactionstarter.society.actor.service.ActorService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;

/**
 * REST endpoints for the two actors directly involved in payments:
 * Resident (payer) and Merchant (external receiver). IDs are never
 * supplied by the client - they are generated by the backend.
 */
@RestController
@RequestMapping("/api/society")
public class ActorController {

    private final ActorService actorService;

    public ActorController(ActorService actorService) {
        this.actorService = actorService;
    }

    @PostMapping("/residents")
    public ResponseEntity<ResidentResponse> createResident(@Valid @RequestBody CreateResidentRequest request) {
        ResidentResponse body = ResidentResponse.from(actorService.createResident(request));
        return ResponseEntity.created(URI.create("/api/society/residents/" + body.getId())).body(body);
    }

    @GetMapping("/residents/{id}")
    public ResidentResponse getResident(@PathVariable String id) {
        return ResidentResponse.from(actorService.getResident(id));
    }

    @PostMapping("/merchants")
    public ResponseEntity<MerchantResponse> createMerchant(@Valid @RequestBody CreateMerchantRequest request) {
        MerchantResponse body = MerchantResponse.from(actorService.createMerchant(request));
        return ResponseEntity.created(URI.create("/api/society/merchants/" + body.getId())).body(body);
    }

    @GetMapping("/merchants/{id}")
    public MerchantResponse getMerchant(@PathVariable String id) {
        return MerchantResponse.from(actorService.getMerchant(id));
    }

    @PostMapping("/admins")
    public ResponseEntity<SocietyAdminResponse> createAdmin(@Valid @RequestBody CreateSocietyAdminRequest request) {
        SocietyAdminResponse body = SocietyAdminResponse.from(
                actorService.createSocietyAdmin(request.getName(), request.getSocietyId(), request.getRole()));
        return ResponseEntity.created(URI.create("/api/society/admins/" + body.getId())).body(body);
    }

    @PostMapping("/property-managers")
    public ResponseEntity<PropertyManagerResponse> createPropertyManager(@Valid @RequestBody CreatePropertyManagerRequest request) {
        PropertyManagerResponse body = PropertyManagerResponse.from(
                actorService.createPropertyManager(request.getName(), request.getSocietyId()));
        return ResponseEntity.created(URI.create("/api/society/property-managers/" + body.getId())).body(body);
    }

    @PostMapping("/guards")
    public ResponseEntity<SecurityGuardResponse> createGuard(@Valid @RequestBody CreateSecurityGuardRequest request) {
        SecurityGuardResponse body = SecurityGuardResponse.from(
                actorService.createSecurityGuard(request.getName(), request.getSocietyId()));
        return ResponseEntity.created(URI.create("/api/society/guards/" + body.getId())).body(body);
    }
}
