package com.example.transactionstarter.society.actor.controller;

import com.example.transactionstarter.society.actor.dto.CreateMerchantRequest;
import com.example.transactionstarter.society.actor.dto.CreateResidentRequest;
import com.example.transactionstarter.society.actor.dto.MerchantResponse;
import com.example.transactionstarter.society.actor.dto.ResidentResponse;
import com.example.transactionstarter.society.actor.service.ActorService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;

/**
 * REST endpoints for the two actors directly involved in payments:
 * Resident (payer) and Merchant (external receiver). IDs are never
 * supplied by the client - they are generated by the backend.
 */
@RestController
@RequestMapping("/api/society")
public class ActorController {

    private final ActorService actorService;

    public ActorController(ActorService actorService) {
        this.actorService = actorService;
    }

    @PostMapping("/residents")
    public ResponseEntity<ResidentResponse> createResident(@Valid @RequestBody CreateResidentRequest request) {
        ResidentResponse body = ResidentResponse.from(actorService.createResident(request));
        return ResponseEntity.created(URI.create("/api/society/residents/" + body.getId())).body(body);
    }

    @GetMapping("/residents/{id}")
    public ResidentResponse getResident(@PathVariable String id) {
        return ResidentResponse.from(actorService.getResident(id));
    }

    @PostMapping("/merchants")
    public ResponseEntity<MerchantResponse> createMerchant(@Valid @RequestBody CreateMerchantRequest request) {
        MerchantResponse body = MerchantResponse.from(actorService.createMerchant(request));
        return ResponseEntity.created(URI.create("/api/society/merchants/" + body.getId())).body(body);
    }

    @GetMapping("/merchants/{id}")
    public MerchantResponse getMerchant(@PathVariable String id) {
        return MerchantResponse.from(actorService.getMerchant(id));
    }
}
