package com.example.transactionstarter.society.actor.service;

import com.example.transactionstarter.society.actor.domain.Merchant;
import com.example.transactionstarter.society.actor.domain.PropertyManager;
import com.example.transactionstarter.society.actor.domain.Resident;
import com.example.transactionstarter.society.actor.domain.SecurityGuard;
import com.example.transactionstarter.society.actor.domain.SocietyAdmin;
import com.example.transactionstarter.society.actor.dto.CreateMerchantRequest;
import com.example.transactionstarter.society.actor.dto.CreateResidentRequest;
import com.example.transactionstarter.society.actor.exception.ActorNotFoundException;
import com.example.transactionstarter.society.actor.repository.MerchantRepository;
import com.example.transactionstarter.society.actor.repository.PropertyManagerRepository;
import com.example.transactionstarter.society.actor.repository.ResidentRepository;
import com.example.transactionstarter.society.actor.repository.SecurityGuardRepository;
import com.example.transactionstarter.society.actor.repository.SocietyAdminRepository;
import org.springframework.stereotype.Service;

/**
 * Creates and looks up society actors (Resident, Merchant, SocietyAdmin,
 * PropertyManager, SecurityGuard). Every actor's ID is generated by the
 * entity's own constructor via {@code IdGenerator} - clients only supply
 * descriptive fields, never an ID.
 */
@Service
public class ActorService {

    private final ResidentRepository residentRepository;
    private final MerchantRepository merchantRepository;
    private final SocietyAdminRepository societyAdminRepository;
    private final PropertyManagerRepository propertyManagerRepository;
    private final SecurityGuardRepository securityGuardRepository;

    public ActorService(ResidentRepository residentRepository,
                         MerchantRepository merchantRepository,
                         SocietyAdminRepository societyAdminRepository,
                         PropertyManagerRepository propertyManagerRepository,
                         SecurityGuardRepository securityGuardRepository) {
        this.residentRepository = residentRepository;
        this.merchantRepository = merchantRepository;
        this.societyAdminRepository = societyAdminRepository;
        this.propertyManagerRepository = propertyManagerRepository;
        this.securityGuardRepository = securityGuardRepository;
    }

    public Resident createResident(CreateResidentRequest request) {
        Resident resident = new Resident(request.getName(), request.getFlatId(), request.getContact());
        return residentRepository.save(resident);
    }

    public Resident getResident(String id) {
        return residentRepository.findById(id)
                .orElseThrow(() -> new ActorNotFoundException("Resident", id));
    }

    public Merchant createMerchant(CreateMerchantRequest request) {
        Merchant merchant = new Merchant(request.getBusinessName(), request.getCategory(), request.getSettlementAccount());
        return merchantRepository.save(merchant);
    }

    public Merchant getMerchant(String id) {
        return merchantRepository.findById(id)
                .orElseThrow(() -> new ActorNotFoundException("Merchant", id));
    }

    public SocietyAdmin createSocietyAdmin(String name, String societyId, String role) {
        return societyAdminRepository.save(new SocietyAdmin(name, societyId, role));
    }

    public PropertyManager createPropertyManager(String name, String societyId) {
        return propertyManagerRepository.save(new PropertyManager(name, societyId));
    }

    public SecurityGuard createSecurityGuard(String name, String societyId) {
        return securityGuardRepository.save(new SecurityGuard(name, societyId));
    }
}
