package com.example.transactionstarter.CustomTests;

import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import com.example.transactionstarter.society.actor.domain.Merchant;
import com.example.transactionstarter.society.actor.domain.Resident;

/**
 * Verifies that Resident/Merchant IDs are generated by the backend
 * (never supplied by the caller) and are derived from the entity's own
 * data rather than being purely random.
 */
class ActorIdGenerationTest {

    @Test
    void resident_isCreatedWithoutManuallySuppliedId_andIdReflectsFlatId() {
        Resident resident = new Resident("Asha Rao", "A-101", "9999999999");

        assertNotNull(resident.getId());
        // ID should contain traceable info from the flat ID, not be arbitrary.
        assertTrue(resident.getId().contains("A101") || resident.getId().contains("RES"));
    }

    @Test
    void twoResidentsWithDifferentData_getDifferentIds() {
        Resident resident1 = new Resident("Asha Rao", "A-101", "9999999999");
        Resident resident2 = new Resident("Vikram Shah", "B-202", "8888888888");

        assertNotEquals(resident1.getId(), resident2.getId());
    }

    @Test
    void merchant_isCreatedWithoutManuallySuppliedId() {
        Merchant merchant = new Merchant("Sunrise Salon", "SALON", "ACC-001");

        assertNotNull(merchant.getId());
        assertTrue(merchant.getId().startsWith("MER-"));
    }
}
