package com.example.transactionstarter.society.actor.dto;

import jakarta.validation.constraints.NotBlank;

/** Client-supplied data needed to create a SecurityGuard. No ID is accepted here; it is generated by the backend. */
public class CreateSecurityGuardRequest {

    @NotBlank(message = "name is required")
    private String name;

    @NotBlank(message = "societyId is required")
    private String societyId;

    public CreateSecurityGuardRequest() {
    }

    public CreateSecurityGuardRequest(String name, String societyId) {
        this.name = name;
        this.societyId = societyId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSocietyId() {
        return societyId;
    }

    public void setSocietyId(String societyId) {
        this.societyId = societyId;
    }
}
