package com.example.transactionstarter.society.actor.dto;

import jakarta.validation.constraints.NotBlank;

/** Client-supplied data needed to create a Merchant. No ID is accepted here; it is generated by the backend. */
public class CreateMerchantRequest {

    @NotBlank(message = "businessName is required")
    private String businessName;

    @NotBlank(message = "category is required")
    private String category;

    @NotBlank(message = "settlementAccount is required")
    private String settlementAccount;

    public CreateMerchantRequest() {
    }

    public CreateMerchantRequest(String businessName, String category, String settlementAccount) {
        this.businessName = businessName;
        this.category = category;
        this.settlementAccount = settlementAccount;
    }

    public String getBusinessName() {
        return businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getSettlementAccount() {
        return settlementAccount;
    }

    public void setSettlementAccount(String settlementAccount) {
        this.settlementAccount = settlementAccount;
    }
}
