package com.example.transactionstarter.society.actor.dto;

import jakarta.validation.constraints.NotBlank;

/** Client-supplied data needed to create a SocietyAdmin. No ID is accepted here; it is generated by the backend. */
public class CreateSocietyAdminRequest {

    @NotBlank(message = "name is required")
    private String name;

    @NotBlank(message = "societyId is required")
    private String societyId;

    @NotBlank(message = "role is required")
    private String role;

    public CreateSocietyAdminRequest() {
    }

    public CreateSocietyAdminRequest(String name, String societyId, String role) {
        this.name = name;
        this.societyId = societyId;
        this.role = role;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSocietyId() {
        return societyId;
    }

    public void setSocietyId(String societyId) {
        this.societyId = societyId;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
}
