package com.example.transactionstarter.society.actor.dto;

import jakarta.validation.constraints.NotBlank;

/** Client-supplied data needed to create a Resident. No ID is accepted here; it is generated by the backend. */
public class CreateResidentRequest {

    @NotBlank(message = "name is required")
    private String name;

    @NotBlank(message = "flatId is required")
    private String flatId;

    @NotBlank(message = "contact is required")
    private String contact;

    public CreateResidentRequest() {
    }

    public CreateResidentRequest(String name, String flatId, String contact) {
        this.name = name;
        this.flatId = flatId;
        this.contact = contact;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFlatId() {
        return flatId;
    }

    public void setFlatId(String flatId) {
        this.flatId = flatId;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }
}
